name: Build Base Dev Container
on:
#  workflow_dispatch:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./.devcontainer
        file: .devcontainer/base.Dockerfile
        push: true
        build-args: |
            VERSION=8
        tags: |
          ${{ github.repository_owner }}/dev-container:3.0
    
